const express= require('express');
const checkAuth=require('./middleware/check-auth');
const Auth=require('./controllers/auth');
const crud=require('./controllers/crud');
const router = express.Router();
router.post('/signup',Auth.signup);
router.post('/newSupplier',Auth.newSupplier);
router.post('/login',Auth.Login);
router.post('/getUser',Auth.getUser);
router.post('/authLive',Auth.authLive);
router.post('/authLiveRequest',Auth.authLiveRequest);
router.post('/RemoveauthLiveRequest',Auth.removeLiveReq);
router.post('/removeUnwantedTokens',Auth.removeUnwantedTokens);
router.post('/removeUser',Auth.removeSupplier);
router.post('/storeDetails',Auth.storeDetails);
router.post('/employees',Auth.employees);
router.post('/OrderCompletion',checkAuth,crud.orderCompletion);
router.post('/addressCollection',checkAuth,crud.addressCollection);
module.exports=router;